import streamlit as st
import joblib
import time

# Page configuration
st.set_page_config(page_title="AI vs Human Detector", page_icon=":robot_face:", layout="wide")

@st.cache(allow_output_mutation=True)
def load_model():
    model = joblib.load('models/logistic_regression_model.pkl')
    return model

model = load_model()

def predict(text):
    # This function takes a text input and returns the model's prediction
    return model.predict([text])[0]

# Main header
st.title('AI :robot_face: vs Human :smiley: Detector')
st.markdown("""
This application uses machine learning to predict whether a text was generated by an AI (GPT) or written by a human.
Enter some text below and let the AI analyze whether the content seems to be written by an artificial intelligence or a real person.
""")

# User text input
with st.container():
    user_input = st.text_area("Enter the text to analyze here:", height=150, placeholder="Type or paste text here...")

# Prediction button
if st.button('Predict :mag:'):
    with st.spinner('Analyzing...'):
        start_time = time.time()
        label = predict(user_input)
        end_time = time.time()
        st.write(f"Inference time: {end_time - start_time} seconds")
        
    if label == 0:
        st.success('### Result: Text generated by AI :robot_face:')
    else:
        st.success('### Result: Text written by a human :smiley:')

# About the application
with st.expander("ℹ️ - About This Application"):
    st.write("""
    This application is part of a research project on the ability of machine learning models to distinguish texts generated by humans from those generated by GPT-type algorithms. The models have been trained on a variety of datasets to improve their accuracy.
    """)

# Footer
st.markdown("---")
st.markdown("🚀 Application developed by Julien OHANA, Prisca RAMANANTOANINA, Sofiane EL FARTASS, Enzo NATALI, Maël REYNAUD")
